spring:
  application:
    name: usuario-service
  cloud:
    config:
      enable: true
      uri: http://localhost:8888
eureka.instance.prefer-ip-address=true: true
eureka:
  instance:
    hostname: localhost